ARG IMAGE_VERSION=latest
ARG USERNAME=node

FROM mcr.microsoft.com/devcontainers/typescript-node:${IMAGE_VERSION}

USER node

RUN sudo mkdir -p /devcontainer \
    && sudo mkdir -p /commandhistory \
    && mkdir -p $HOME/.npm \
    && mkdir -p $HOME/.pnpm-store \
    && mkdir -p $HOME/.cache/yarn \
    && mkdir -p $HOME/.nuget 

RUN npm i --location=global npm yarn pnpm @cpdevtools/dcman-cli \
    && pnpm config set store-dir $HOME/.pnpm-store

VOLUME [ "/devcontainer",  "/commandhistory", "${HOME}/.npm", "${HOME}/.pnpm-store",  "${HOME}/.cache/yarn", "$HOME/.nuget"]
RUN sudo chown -R node:node /devcontainer /commandhistory $HOME

RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R vscode /commandhistory \
    && echo $SNIPPET >> "/home/vscode/.bashrc"

CMD [ "sleep", "infinity" ]