ARG IMAGE_VERSION=18-bullseye

FROM mcr.microsoft.com/devcontainers/typescript-node:${IMAGE_VERSION}

USER node

RUN sudo mkdir -p /devcontainer \
    && sudo mkdir -p /commandhistory \
    && mkdir -p $HOME/.npm \
    && mkdir -p $HOME/.pnpm-store \
    && mkdir -p $HOME/.cache/yarn

RUN sudo chown -R node:node /devcontainer /commandhistory $HOME

ENV SHELL=/bin/bash
ENV PNPM_HOME=/home/node/.pnpm-store
ENV PATH=$PATH:$PNPM_HOME

RUN npm i --location=global npm yarn pnpm \
    && pnpm config set store-dir $HOME/.pnpm-store \
    && pnpm setup
    
RUN . /home/node/.bashrc \
    && pnpm --global install @angular/cli@16 \
    && ng analytics disable --global \
    && ng completion \
    && ng config cli.packageManager pnpm --global

VOLUME [ "/devcontainer",  "/commandhistory", "${HOME}/.npm", "${HOME}/.pnpm-store",  "${HOME}/.cache/yarn"]

CMD [ "sleep", "infinity" ]