ARG VERSION=latest
ARG USERNAME=node

FROM ghcr.io/cpdevtools/base-dc-image:${VERSION}

USER node

RUN sudo mkdir -p /devcontainer \
    && sudo mkdir -p /commandhistory \
    && mkdir -p $HOME/.npm \
    && mkdir -p $HOME/.pnpm-store \
    && mkdir -p $HOME/.cache/yarn

RUN npm i --location=global npm yarn pnpm @cpdevtools/dcman-cli \
    && pnpm config set store-dir $HOME/.pnpm-store

VOLUME [ "/devcontainer",  "/commandhistory", "${HOME}/.npm", "${HOME}/.pnpm-store",  "${HOME}/.cache/yarn"]
RUN sudo chown -R node:node /devcontainer /commandhistory $HOME

CMD [ "sleep", "infinity" ]