ARG IMAGE_VERSION=latest
FROM mcr.microsoft.com/devcontainers/dotnet:${IMAGE_VERSION}

USER vscode

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
    && export NVM_DIR="/usr/local/share/nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
    && nvm install 18  

RUN npm i --location=global npm yarn pnpm \
    && pnpm config set store-dir $HOME/.pnpm-store


VOLUME [ "/devcontainer",  "/commandhistory", "${HOME}/.npm", "${HOME}/.pnpm-store",  "${HOME}/.cache/yarn", "${HOME}/.nuget"]
RUN chown -R vscode:vscode /devcontainer $HOME

CMD [ "sleep", "infinity" ]
