ARG IMAGE_VERSION=latest
FROM mcr.microsoft.com/devcontainers/dotnet:${IMAGE_VERSION}

USER vscode

RUN sudo mkdir -p /devcontainer \
    && sudo mkdir -p /commandhistory \
    && mkdir -p $HOME/.npm \
    && mkdir -p $HOME/.pnpm-store \
    && mkdir -p $HOME/.cache/yarn \
    && mkdir -p $HOME/.nuget

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
    && export NVM_DIR="/usr/local/share/nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" \
    && nvm install 16.18.1 \
    && nvm install 18.18.0  

RUN npm i --location=global npm yarn pnpm @cpdevtools/dcman-cli \
    && pnpm config set store-dir $HOME/.pnpm-store

VOLUME [ "/devcontainer",  "/commandhistory", "${HOME}/.npm", "${HOME}/.pnpm-store",  "${HOME}/.cache/yarn", "${HOME}/.nuget"]
RUN sudo chown -R vscode:vscode /devcontainer /commandhistory $HOME

CMD [ "sleep", "infinity" ]
