version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock