name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  pack_dotnet:
    name: Publish dotnet
    uses: "cpdevtools/common-github-workflows/.github/workflows/pnpm-publish-docker.yml@main"
    with:
      projectName: "dotnet"

  # fixes an issue with the external actions/workflows not being able to create/publish a release that is not draft
  publish_release:
    runs-on: ubuntu-latest
    needs: pack_dotnet
    steps:
      - uses: eregon/publish-release@v1
        with:
          release_id: ${{ needs.pack_dotnet.outputs.releaseId }}
