name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  build-dotnet:
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-build-and-publish-projects.yml@main
    name: dotnet
    with:
      projectFilter: "dotnet"
