name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - "release/*"

jobs:
  pack_dotnet:
    if: github.event.pull_request.merged == true
    name: Publish dotnet
    uses: "cpdevtools/common-github-workflows/.github/workflows/pnpm-publish-docker.yml@main"
    with:
      projectName: "dotnet"

  # fixes an issue with the external actions/workflows not being able to create/publish a release that is not draft
  publish_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: pack_dotnet
    steps:
      - uses: eregon/publish-release@v1
        with:
          release_id: ${{ needs.pack_dotnet.outputs.releaseId }}
