name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  build-dotnet:
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-pack-docker.yml@main
    name: dotnet
    with:
      projectName: "dotnet"
