name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  pack_dotnet:
    name: Publish dotnet
    uses: "cpdevtools/common-github-workflows/.github/workflows/pnpm-publish-docker.yml@main"
    with:
      projectName: "dotnet"

  publish_release:
    runs-on: ubuntu-latest
    needs: pack_dotnet
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.githubToken }}
        with:
          release_id: ${{ needs.pack_dotnet.outputs.releaseId }}
