name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  pack-dotnet:
    name: Pack dotnet
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-pack-.yml@main
    with:
      projectName: "dotnet"
