name: Publish

on:
  push:
    branches:
      - "release/*"

jobs:
  pack-dotnet:
    name: Publish dotnet
    uses: "cpdevtools/common-github-workflows/.github/workflows/pnpm-publish-docker.yml@main"
    with:
      projectName: "dotnet"
