name: Run Tests on PR push

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "release/*"

jobs:
  build-dotnet:
    name: dotnet
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-build-and-test-projects.yml@main
    with:
      projectFilter: "dotnet"
