name: Check PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "release/*"

jobs:
  pr_check_version:
    name: Check that version is valid
    uses: cpdevtools/common-github-workflows/.github/workflows/pr-check-version.yml@main
