name: Check that the PR version is valid

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "release/*"

jobs:
  build-dotnet:
    name: dotnet
    runs-on: ubuntu-latest
    uses: cpdevtools/common-github-workflows/.github/actions/check-version.yml@main
    with:
      projectFilter: "dotnet"
