name: Test PR Events

on:
  pull_request:
    types:
      - closed

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
