name: Test

on:
  push:
    branches:
      - "*"
      - "v/*"

jobs:
  build-dotnet:
    name: "Build and test project: dotnet"
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-build-and-test-projects.yml@main
    with:
      projectFilter: "dotnet"
  build-dotnet-ng:
    name: "Build and test project: dotnet-ng"
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-build-and-test-projects.yml@main
    with:
      projectFilter: "dotnet-ng"
