name: Test

on:
  push:
    branches:
      - "*"
      - "v/*"

jobs:
  build-dotnet:
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-build-and-test-projects.yml@main
    name: Build and test dotnet
    with: 
      projectFilter: "dotnet"
  build-dotnet-ng:
    uses: cpdevtools/common-github-workflows/.github/workflows/pnpm-build-and-test-projects.yml@main
    name: Build and test dotnet-ng
    with: 
      projectFilter: "dotnet-ng"
